# markdown:  kramdown
# markdown: rdiscount
permalink: /:year/:month/:title/
url: http://rainlandlee.github.io
author: Rain
# highlighter: rouge
# highlighter: pygments
gems: [jekyll-paginate]
paginate: 24
paginate_path: "page:num"
